#spring:
#  jpa:
#    show-sql: true

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate.type.descriptor.sql: trace