spring:
  datasource:
    username: bookuser
    password: password
    url: jdbc:mysql://localhost:3306/bookdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
  flyway:
    user: bookadmin
    password: password