DROP DATABASE IF EXISTS bookdb;
DROP USER IF EXISTS 'bookadmin'@'%';
DROP USER IF EXISTS 'bookuser'@'%';
CREATE DATABASE IF NOT EXISTS bookdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'bookadmin'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSER, UPDATE, DELETE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON 'bookdb'.* TO 'bookadmin'@'%';
CREATE USER IF NOT EXIST 'bookuser'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT,INSER, UPDATE, DELETE, SHOW VIEW ON 'bookdb'.* TO 'bookuser'@'%';
FLUSH PRIVILEGES;
